import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ko_KR': {
          'start': '시작하기',
          'credit': 'Credit',
          'create_a_olchaeneez_wallet': '올채니즈 지갑을 만들어 보세요!',
          'craete_olchaeneez_wallet_text':
              '올채니즈는 깨끗한 환경에서 건강하게 자라납니다. 휴대폰 배터리 사용을 줄일수록 연못의 환경이 더 좋아져요.  환경을 깨끗하게 하고 올채니즈를 건강하게 키워 더 많은 보상을 받으세요!',
          'create_a_wallet': '지갑 만들기',
          'private_key': '개인키',
          'add_account': '계정 추가',
          'add_account_text': '가져올 계정의 개인키를 입력해주세요.',

          'password_text1': '비밀번호 6자리를 설정해 주세요',
          'password_text2': '비밀번호 6자리를 입력해 주세요',
          'password': '비밀번호',
          'password_check': '입력하신 비밀번호를 확인해주세요',
          'password_notice':
              '비밀번호는 서버에 저장되지 않습니다. 비밀번호를 잃어버릴 시 복구가 불가하니 주의해 주세요.',
          'password_notice_check': '아래 체크 박스를 읽고 체크해주세요',
          'confirm_password_text1': '한 번 더 입력해 주세요.',
          'made_wallet': '지갑이  만들어졌어요!',
          'grow_a_olchaeneez': '올채니즈 키우기',
          'select_egg': '키우실 알을 선택하세요.',
          'ggnz_egg': '보통 알',
          'special_egg': '특별한 알',
          'premium_egg': '프리미엄 알',
          'need_gog': 'GOG 전용',
          'need_gop': 'GOP 전용',
          'wake_up': '잠 깨우기',
          'buy_egg': '알 구매하기',
          'buy_egg_question': '알을 구매하시겠습니까?',
          'yes': '네',
          'no': '아니오',
          'item_dialog_text':
              '특별한 아이템으로 올채니를 더 건강하게 성장시킬 수 있어요.  아이템을 선택해 볼까요?',
          'empty_item_dialog_text':
              '특별한 아이템으로 올채니를 더 건강하게 성장시킬 수 있어요.   앗 사용 가능한 아이템이 없네요.  플레이 전에 상점을 방문하시겠습니까?',
          'continue': '계속',
          'item_shop': '상점',
          'egg': '알',
          'buy_box': '상자를 구매하시겠습니까?',
          'open_box': '상자 열기',
          'random_box_purchase_completed': '-랜덤상자 구매완료!-',
          'go_to_inventory': '인벤토리로 이동',
          'wallet': '지갑',
          'purchase': '구매하기',
          'exchange': '교환하기',
          'dispatch': '방생하기',
          'growth_complete': '성장완료',
          'reward_for_dispatch': '방생하면 얻는 보상',
          'energy_saving_time': '에너지를 절약한 시간',
          'give_up_dispatch': '방생을 포기하고 나의 올채니를 입양하여 NFT로 남깁니다.',
          'need_some_tokens': '약간의 토큰이 필요합니다.',
          'adopt': '입양하기',
          'Vitamin Ade': '비타민 에이드',
          'Vitamin Ade Description': '건강도가 +30만큼  증가합니다.',
          'Taurine Ade': '타우린 에이드',
          'Taurine Ade Description': '건강도가 +50만큼  증가합니다.',
          'Mixed Ade': '뿅뿅 에이드',
          'Mixed Ade Description': '건강도가 +100만큼  증가합니다.',
          'Clean Pill': '깨끗하게 정화제',
          'Clean Pill Description': '환경 게이지가 +30만큼  증가합니다.',
          'Clear Pill': '맑게 정화제',
          'Clear Pill Description': '환경 게이지가 +60만큼  증가합니다.',
          'Clean&Clear Packet': '자신있게 정화제',
          'Clean&Clear Packet Description': '환경 게이지가 +100만큼  증가합니다.',
          'General Air Purifier': '일반 공기청정기',
          'General Air Purifier Description': '분당 10%의 건강도가  추가로 증가합니다.',
          'Fresh Air Purifier': '상쾌 공기청정기',
          'Fresh Air Purifier Description': '분당 20%의 건강도가  추가로 증가합니다.',
          'Health Air Purifier': '건강 공기청정기',
          'Health Air Purifier Description': '분당 40%의 건강도가  추가로 증가합니다.',
          'Panacea Air Purifier': '만병통치 공기청정기',
          'Panacea Air Purifier Description': '분당 80%의 건강도가  추가로 증가합니다.',
          'Immortal Air Purifier': '불로불사 공기청정기',
          'Immortal Air Purifier Description': '분당 120%의 건강도가  추가로 증가합니다.',
          'White Motor': '화이트 모터',
          'White Motor Description': '분당 20%의 환경게이지가  추가로 증가합니다.',
          'Black Motor': '블랙 모터',
          'Black Motor Description': '분당 40%의 환경게이지가  추가로 증가합니다.',
          'Tuning Motor': '튜닝 모터',
          'Tuning Motor Description': '분당 60%의 환경게이지가  추가로 증가합니다.',
          'Dash Motor': '대쉬 모터',
          'Dash Motor Description': '분당 80%의 환경게이지가  추가로 증가합니다.',
          'Alloy Motor': '합금 모터',
          'Alloy Motor Description': '분당 100%의 환경게이지가  추가로 증가합니다.',
          'Gold Motor': '순금 모터',
          'Gold Motor Description': '분당 120%의 환경게이지가  추가로 증가합니다.',
          //______
          'inventory': '인벤토리',
          'box': '상자',
          'Wood Random Box': '나무 랜덤 상자',
          'Wood Random Box Description':
              '이 상자에는 올채니즈 성장에 도움이 되는 잡동사니가 랜덤하게 담겨 있습니다.',
          'Iron Random Box': '철 랜덤 상자',
          'Iron Random Box Description':
              '이 상자에는 올채니즈 성장에 도움이 되는 잡동사니가 랜덤하게 담겨 있습니다. 좀 더 특별한 잡동사니가 담겨 있을지 몰라요.',
          'everyone': '누구나 키울 수 있는 보통의 알입니다.',
          'gop_holder_only': 'GOP 전용 좀 더 건강한 개구니의 알입니다. ',
          'gop_holder_only_message': 'GOP 홀더 전용 상품입니다.',
          'gog_holder_only': 'GOG 전용 건강한 개구니의 알입니다.',
          'gog_holder_only_message': 'GOG 홀더 전용 상품입니다.',
          'request_permission_to_work': '작업 권한을 요청합니다',
          'environment_gauge': '환경게이지',
          'health_level': '건강도',
          'per_minute': '1분당',
          'increase': '증가',
          'check_what_item_was_found': '무슨 아이템이 나왔는지 확인해 보세요',
          'egg_purchase_complete': '알 구매완료!',
          'exchange_coin': '토큰을 교환하시겠습니까?',
          'exchange_complete': '토큰 교환 완료!',
          'dispatch_start': '올채니를 방생하시겠습니까?',
          'dispatch_complete': '방생 완료!',
          'OCNZ Mint': '민팅권',
          'OCNZ Mint Description': '성장을 끝낸  올채니를 입양합니다.',
          'minting_complete': '입양 완료!',
          'minting_failed': '동일한 NFT가 존재하여 민팅에 실패했습니다.',
          'already_running_service': '다른 작업을 진행 중 입니다. 잠시 후에 시도해주세요.',
          'check_egg': '이전에 키우던 올채니를 이어서 키우시겠습니까?',
          'check_dispatch': '방생 중이던 올채니를 이어서 방생하시겠습니까?',
          'check_minting': '입양 중이던 올채니를 이어서 입양 하시겠습니까?',
          'copy_address': '클립보드에 복사되었습니다.',
          'olchaeneez_guide': '올채니즈 성장 가이드',
          'not_enough_gas': '수수료로 사용할 Klay가 부족합니다.',
          'not_enough_gas_awake': '잠을 깨우기 위해 준비중입니다.',
          'not_enough_items': '알 또는 아이템의 수량이 부족합니다.',
          'loading_ads': '시청할 광고가 없습니다. 잠시 후 시도해주세요.',
          'contact_administrator': '오류가 발생했습니다. 관리자에게 문의해주세요.',
          'not_enough_token': '보유한 토큰 수량이 부족합니다.',
          'private_key_export': '개인키를 복사하시겠습니까?',
          'service_restart_with_error': '서비스가 불안정하여 다시 시도합니다. 잠시만 기다려주세요.',
          'get_rewards': '보상을 받으시겠습니까?',
          'wants_to_buy_egg': '깨울 알이 없습니다. 알 구매란으로 이동하시겠습니까?',
          'dispatch_device_error': '이미 파견된 올채니 입니다.',
        },
        'en_US': {
          'start': 'start',
          'credit': 'Credit',
          'create_a_olchaeneez_wallet': 'Create a Olchaeneez wallet!',
          'craete_olchaeneez_wallet_text':
              'Olchaeneez grows healthy in a clean environment. The less you use your phone battery, the better the pond environment becomes.  Clean the environment and grow a healthy Olchaeneez for more rewards!',
          'create_a_wallet': 'create_a_wallet',
          'private_key': 'Private Key',
          'add_account': 'Add Account',
          'add_account_text': 'Enter the private key of the account to import.',
          'password_text1': 'Please set a 6-digit password',
          'password_text2': 'Please enter a 6-digit password',
          'password': 'Password',
          'password_check': 'Please check the password you entered',
          'password_notice':
              'Passwords are not stored on the server. Please note that if you lose your password, it cannot be recovered.',
          'password_notice_check': 'Please read and tick the checkboxes below',
          'confirm_password_text1': 'Please input one more time.',
          'made_wallet': 'Your wallet is created!',
          'grow_a_olchaeneez': 'Grow a Olchaeneez',
          'select_egg': 'Choose which egg to grow',
          'ggnz_egg': 'Gaeguneez egg',
          'special_egg': 'Special egg',
          'premium_egg': 'Premium egg',
          'need_gog': 'GOG is needed!',
          'need_gop': 'GOP is needed!',
          'wake_up': 'Wake Up',
          'buy_egg': 'Buy egg',
          'buy_egg_question': 'Would you like to purchase an egg?',
          'yes': 'Yes',
          'no': 'No',
          'item_dialog_text':
              'You can grow Olchaeneez healthier with special items.  Do you want to select an item?',
          'continue': 'Continue',
          'item_shop': 'Item Shop',
          'egg': 'Egg',
          'buy_box': 'Would you like to purchase a box?',
          'open_box': 'Open Box',
          'random_box_purchase_completed': '-Random box purchase completed!-',
          'go_to_inventory': 'Go to Inventory',
          'wallet': 'Wallet',
          'purchase': 'Purchase',
          'exchange': 'Exchange',
          'dispatch': 'Dispatch',
          'growth_complete': 'Complete',
          'reward_for_dispatch': 'Reward for Dispatch',
          'energy_saving_time': 'Energy-saving time',
          'give_up_dispatch':
              'Give up dispatching, adopt my Olchaeneez, and leave it as NFT.',
          'need_some_tokens': 'Some tokens are required',
          'adopt': 'Adopt',
          'Vitamin Ade': 'Vitamin Ade',
          'Vitamin Ade Description': '30 points increase  in health level',
          'Taurine Ade': 'Taurine Ade',
          'Taurine Ade Description': '50 points increase  in health level',
          'Mixed Ade': 'Mixed Ade',
          'Mixed Ade Description': '100 points increase  in health level',
          'Clean Pill': 'Clean Pill',
          'Clean Pill Description':
              '30 points increase  in environmental gauge',
          'Clear Pill': 'Clear Pill',
          'Clear Pill Description':
              '60 points increase  in environmental gauge',
          'Clean&Clear Packet': 'Clean&Clear Packet',
          'Clean&Clear Packet Description':
              '100 points increase  in environmental gauge',
          'General Air Purifier': 'General Air Purifier',
          'General Air Purifier Description':
              'Additional 10% increase  in health level per minute',
          'Fresh Air Purifier': 'Fresh Air Purifier',
          'Fresh Air Purifier Description':
              'Additional 20% increase  in health level per minute',
          'Health Air Purifier': 'Health Air Purifier',
          'Health Air Purifier Description':
              'Additional 40% increase  in health level per minute',
          'Panacea Air Purifier': 'Panacea Air Purifier',
          'Panacea Air Purifier Description':
              'Additional 80% increase  in health level per minute',
          'Immortal Air Purifier': 'Immortal Air Purifier',
          'Immortal Air Purifier Description':
              'Additional 120% increase  in health level per minute',
          'White Motor': 'White Motor',
          'White Motor Description':
              'Additional 20% increase  in environmental gauge per minute',
          'Black Motor': 'Black Motor',
          'Black Motor Description':
              'Additional 40% increase  in environmental gauge per minute',
          'Tuning Motor': 'Tuning Motor',
          'Tuning Motor Description':
              'Additional 60% increase  in environmental gauge per minute',
          'Dash Motor': 'Dash Motor',
          'Dash Motor Description':
              'Additional 80% increase  in environmental gauge per minute',
          'Alloy Motor': 'Alloy Motor',
          'Alloy Motor Description':
              'Additional 100% increase  in environmental gauge per minute',
          'Gold Motor': 'Gold Motor',
          'Gold Motor Description':
              'Additional 120% increase  in environmental gauge per minute',
          //______
          'box': 'Box',
          'Wood Random Box': 'Wood Random Box',
          'Wood Random Box Description':
              'This random box contains Misc, which helps Olchaenez grow.',
          'Iron Random Box': 'Iron Random Box',
          'Iron Random Box Description':
              'This random box contains Misc, which helps Olchaenez grow. It might contain something more special. ◡̈ ',
          'everyone': 'everyone',
          'gop_holder_only': 'gop holder',
          'gop_holder_only_message': 'This product is only for GOP holders',
          'gog_holder_only': 'gog holder',
          'gog_holder_only_message': 'This product is only for GOG holders',
          'inventory': 'INVENTORY',
          'request_permission_to_work': 'Request permission  to work',
          'environment_gauge': 'environment gauge',
          'health_level': 'health level',
          'per_minute': 'per minute',
          'increase': 'increase',
          'check_what_item_was_found': 'Check what item was found',
          'egg_purchase_complete': 'Egg purchase complete!',
          'exchange_coin': 'Would you like to exchange your coins?',
          'exchange_complete': '-coin exchange completed!-',
          'dispatch_start': 'Would you like to dispatch you Olchaeneez?',
          'dispatch_complete': '-dispatch completed!-',
          'OCNZ Mint': 'OCNZ Mint',
          'OCNZ Mint Description':
              'Mint the Olchaeneez  that has finished growing',
          'minting_complete': '-minting completed!-',
          'minting_failed': 'Minting failed because the same NFT exists.',
          'already_running_service':
              'Another task is in progress. Please try again later.',
          'check_egg':
              'Do you want to continue raising Olchaeneez that you used to raise?',
          'check_dispatch':
              'Do you want to dispatch Olchaeneez that you used to raise?',
          'check_minting':
              'Do you want to mint Olchaeneez that you used to raise?',
          'copy_address': 'Copied to clipboard.',
          'olchaeneez_guide': 'Olchaeneez Growth Guide',
          'not_enough_gas': 'There is not enough Klay to use as a gas fee.',
          'not_enough_gas_awake': 'Getting ready to wake it up.',
          'not_enough_items': 'There is not enough Egg or item to use.',
          'loading_ads': 'There are no ads to watch. Please try it later.',
          'contact_administrator':
              'Something went wrong. Please contact the administrator.',
          'not_enough_token': 'There is not enough token to exchange.',
          'private_key_export': 'Do you want to copy the private key?',
          'service_restart_with_error':
              'The service is unstable. Please wait a moment.',
          'wants_to_buy_egg':
              'There are no eggs to wake up. Do you want to go to the egg market?',
          'get_rewards': 'Do you wants to get rewards?',
          'dispatch_device_error': "This Olchaeneez is already dispatched."
        },
      };
}
